Document: okapi
Title: Debian okapi Manual
Author: <insert document author here>
Abstract: This manual describes what okapi is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/okapi/okapi.sgml.gz

Format: postscript
Files: /usr/share/doc/okapi/okapi.ps.gz

Format: text
Files: /usr/share/doc/okapi/okapi.text.gz

Format: HTML
Index: /usr/share/doc/okapi/html/index.html
Files: /usr/share/doc/okapi/html/*.html
